# Степенной метод нахождения собственных чисел и векторов матрицы

In [1]:
import numpy as np
import numpy.linalg as linalg

import warnings
warnings.filterwarnings('ignore')

In [2]:
A = np.array([[-1.536984, -0.199070, 0.958551],
             [-0.199070, 1.177416, 0.069925],
             [0.958551, 0.069925, -1.551506]])

1.

In [3]:
def get_lambda(A, x):
    n = A.shape[0]
    x1 = A @ x
    i = 1
    return x1[i] / x[i]

In [4]:
def get_lambda1(A, e):
    n = A.shape[0]
    Y_k = np.ones((n, 1))
    Y_k1 = A @ Y_k
    l_k = get_lambda(A, Y_k)
    l_k1 = get_lambda(A, Y_k1)
    k = 2
    while abs(l_k1 - l_k) >= e:
        k += 1
        Y_k1 = A @ Y_k1
        l_k = l_k1
        l_k1 = get_lambda(A, Y_k1)
    return l_k1, k

In [5]:
l, k = get_lambda1(A, 10**-5)

In [6]:
l

array([-2.5126064])

In [7]:
k

28

2.

In [8]:
def eytken_method(A, e):
    n = A.shape[0]
    Y_k = np.ones((n, 1))
    Y_k1 = A @ Y_k
    Y_k2 = A @ Y_k1
    l_k = get_lambda(A, Y_k)
    l_k1 = get_lambda(A, Y_k1)
    l_k2 = get_lambda(A, Y_k2)
    k = 3
    while abs(l_k - l_k1) >= e:
        k += 1
        Y_k2 = A @ Y_k2
        l_k1 = (l_k * l_k2 - l_k1 * l_k1) / (l_k - 2 * l_k1 + l_k2)
        l_k3 = get_lambda(A, Y_k2)
        l_k2 = (l_k1 * l_k3 - l_k2 * l_k2) / (l_k1 - 2 * l_k2 + l_k3)
        l_k = l_k1
        l_k1 = l_k2
        l_k2 = l_k3
    return l_k1, k

In [9]:
l, k = eytken_method(A, 10**-5)

In [10]:
l

array([-2.51252989])

In [11]:
k

24

4.

In [12]:
def scalar_product_method(A, e):
    n = A.shape[0]
    Y_k = np.ones((n, 1))
    Y_k1 = A @ Y_k
    Y_k2 = A @ Y_k1
    l_k = (Y_k1.reshape(1, -1) @ Y_k) / (Y_k.reshape(1, -1) @ Y_k)
    l_k1 = (Y_k2.reshape(1, -1) @ Y_k1) / (Y_k1.reshape(1, -1) @ Y_k1)
    k = 3
    while abs(l_k1 - l_k) >= e:
        k += 1
        Y_k1 = Y_k2
        Y_k2 = A @ Y_k1
        l_k = l_k1
        l_k1 = (Y_k2.reshape(1, -1) @ Y_k1) / (Y_k1.reshape(1, -1) @ Y_k1)
    return l_k1, k

In [13]:
l1, k = scalar_product_method(A, 10**-5)

In [14]:
l1

array([[-2.51260288]])

In [15]:
k

16

5.

In [16]:
def do_iter(A, k):
    n = A.shape[0]
    Y_k = np.ones((n, 1))
    for i in range(k):
        Y_k = A @ Y_k
    return Y_k

In [17]:
def get_lambda2(A, l1, k):
    Y_k = do_iter(A, k - 1)
    Y_k1 = A @ Y_k
    Y_k2 = A @ Y_k1
    i = 1
    return (Y_k2[i] - l1 * Y_k1[i]) / (Y_k1[i] - l1 * Y_k[i])

In [18]:
get_lambda2(A, l1, 20)

array([[1.18760669]])

7.

In [19]:
def vilandt_method(A, l1, k):
    n = A.shape[0]
    W = linalg.inv(A - l1 * np.eye(n))
    Y_k = do_iter(W, k)
    Y_k1 = W @ Y_k
    i = 1
    return l1 + Y_k[i] / Y_k1[i]

In [20]:
vilandt_method(A, l1, 20)

array([[-2.51260398]])