# Проекционные методы, метод Ритца

## Вариант 4

In [1]:
import numpy as np

In [2]:
p = lambda x: 1 / (2 * np.sin(x) + 3)
r = lambda x: 2 - x ** 2 / 2
f = lambda x: 1 + x

In [3]:
from scipy.special import jacobi

In [4]:
n = 3

In [5]:
wn = [lambda x: 1 + x] + list(map(lambda k: lambda x: (1 - x ** 2) * jacobi(int(k), 1, 1)(x), list(range(n - 1))))

In [6]:
from scipy.integrate import quad
def integral(F):
    return quad(F, -1, 1)[0]

In [7]:
from scipy.misc import derivative
def derivate(f):
    return lambda x: derivative(f, x, dx=1e-6)

In [8]:
def energy_scalar(y, z):
    global p, r
    return integral(lambda x: p(x) * derivate(y)(x) * derivate(z)(x) + r(x) * y(x) * z(x))

In [9]:
def scalar_L2(y, z):
    return integral(lambda x: y(x) * z(x))

In [10]:
def get_aj(wn, f):
    b = np.array([scalar_L2(f, wk) for wk in wn]).reshape(-1, 1)
    print(b)
    A = np.array([[energy_scalar(wj, wk) for wj in wn] for wk in wn])
    print(A)
    return np.linalg.solve(A, b)

In [11]:
aj = get_aj(wn, f)
aj

[[2.66666667]
 [1.33333333]
 [0.53333333]]
[[ 5.56892833  2.87367832  0.78772536]
 [ 2.87367832  3.19215102 -0.57188506]
 [ 0.78772536 -0.57188506  3.76635242]]


array([[ 0.47315903],
       [-0.00063948],
       [ 0.04254733]])

In [12]:
yn = lambda x: np.sum([aj[j] * wn[j](x) for j in range(len(wn))])

In [13]:
y3 = [yn(i) for i in np.arange(-1, 1.25, 0.25)]

In [14]:
n = 6

In [15]:
wn = [lambda x: 1 + x] + list(map(lambda k: lambda x: (1 - x ** 2) * jacobi(int(k), 1, 1)(x), list(range(n - 1))))

In [16]:
aj = get_aj(wn, f)
aj

[[ 2.66666667e+00]
 [ 1.33333333e+00]
 [ 5.33333333e-01]
 [ 9.71445147e-17]
 [-7.63278329e-17]
 [-8.32667268e-17]]
[[ 5.56892833e+00  2.87367832e+00  7.87725359e-01 -8.01193611e-02
  -5.09332909e-02 -3.68042873e-03]
 [ 2.87367832e+00  3.19215102e+00 -5.71885059e-01 -2.83418355e-01
  -3.72219634e-02  2.15752762e-02]
 [ 7.87725359e-01 -5.71885059e-01  3.76635242e+00 -1.08244529e+00
  -4.13122652e-02 -6.45366546e-02]
 [-8.01193611e-02 -2.83418355e-01 -1.08244529e+00  5.08646246e+00
  -1.60088612e+00  1.82359706e-01]
 [-5.09332909e-02 -3.72219634e-02 -4.13122652e-02 -1.60088612e+00
   6.53663710e+00 -2.12125777e+00]
 [-3.68042873e-03  2.15752762e-02 -6.45366546e-02  1.82359706e-01
  -2.12125777e+00  8.04959195e+00]]


array([[0.46815342],
       [0.00746689],
       [0.05126062],
       [0.021832  ],
       [0.0102758 ],
       [0.00281833]])

In [17]:
yn = lambda x: np.sum([aj[j] * wn[j](x) for j in range(len(wn))])

In [18]:
y6 = [yn(i) for i in np.arange(-1, 1.25, 0.25)]

In [20]:
np.abs(np.array(y6) - np.array(y3))

array([0.        , 0.00622249, 0.00336012, 0.004279  , 0.01151178,
       0.0109561 , 0.00179088, 0.0164723 , 0.01001122])