In [130]:
import numpy as np
import numpy.linalg as linalg

## №1

$Ax = b$

$A\overline x = b + \Delta b$

$b = (200, -600)^{T}$

$\Delta b = (-1, -1)^{T}$

$\mu(A)- ?$

$\displaystyle \delta x = \frac {\| \overline{x} - x \|} {\| x \|} = ?$

И оценить теоретическую: $\delta x \le \mu(A)\delta b$

### Формула Крамера

$\displaystyle x_1 =\frac {\Delta_{x_1}} {\Delta} \\
\displaystyle x_2 =\frac {\Delta_{x_2}} {\Delta} \\
\cdots \\
\displaystyle x_n =\frac {\Delta_{x_n}} {\Delta}$

$\Delta x_i = \begin{vmatrix}
a_{11} & \dots & b_{1} & \dots & a_{1n} \\ 
\vdots & \vdots & \vdots & \vdots & \vdots \\ 
\vdots & \vdots & \vdots & \vdots & \vdots \\
\vdots & \vdots & \vdots & \vdots & \vdots \\ 
a_{n1} & \dots & b_{n} & \dots & a_{nn}  \notag
\end{vmatrix}$

На "итом" месте.

#### Вариант 6

In [131]:
A = np.array([[-402.50, 200.5], 
              [1203., -603.]])

In [132]:
def Cramer2(A, b):
    det_A = linalg.det(A)
    det_dx1 = linalg.det(np.column_stack([b, A[:, 1]]))
    det_dx2 = linalg.det(np.column_stack([A[:, 0], b]))
    x1 = det_dx1 / det_A
    x2 = det_dx2 / det_A
    return np.array([x1, x2])

In [133]:
b = np.array([200, -600])
db = np.array([-1, -1])

In [134]:
x = Cramer2(A, b)
x

array([-0.19920319,  0.59760956])

In [135]:
x_broken = Cramer2(A, b + db)
x_broken

array([0.33432935, 1.66367862])

In [136]:
delta_x = linalg.norm(x_broken - x, ord=np.inf) / linalg.norm(x, ord=np.inf)
delta_x

1.7838888888889095

In [137]:
linalg.cond(A, p=np.inf), linalg.det(A)

(1925.3207171314757, 1505.9999999999986)

Слабая оценка через число обусловленности

In [138]:
error_score = linalg.cond(A, p=np.inf) * linalg.norm(db, ord=np.inf) / linalg.norm(b, ord=np.inf)
error_score

3.2088678618857926

Более точная оценка погрешности

In [139]:
delta_b = linalg.norm(db, ord=np.inf) / linalg.norm(b, ord=np.inf)
alfa = linalg.norm(linalg.inv(A), ord=np.inf) * linalg.norm(b, ord=np.inf) / linalg.norm(x, ord=np.inf)
more_attractive_error_score = alfa * delta_b
more_attractive_error_score

1.783888888888887

## №2

In [140]:
b = np.array([199, -601])
cramer = Cramer2(A, b)
cramer[0], cramer[1]

(0.33432934926958957, 1.6636786188579173)

In [141]:
def Gauss2(A, b):
    a12_1 = A[0, 1] / A[0, 0]
    b1_1 = b[0] / A[0, 0]
    a22_1 = A[1, 1] - A[1, 0] * a12_1
    b2_1 = b[1] - A[1, 0] * b1_1
    b2_2 = b2_1 / a22_1
    x2 = b2_2
    x1 = b1_1 - a12_1 * x2
    return np.array([x1, x2])

In [142]:
gauss = Gauss2(A, b)
gauss[0], gauss[1]

(0.334329349269588, 1.6636786188579011)

In [143]:
cramer_bad = Cramer2(A - 500*np.eye(A.shape[0]), b)
cramer_bad[0], cramer_bad[1]

(-0.13125053032392187, 0.40172766275641164)

In [144]:
gauss_bad = Gauss2(A - 500*np.eye(A.shape[0]), b)
gauss_bad[0], gauss_bad[1]

(-0.1312505303239218, 0.4017276627564117)

## №3

In [145]:
b = np.array([200, 420])
x = Gauss2(A, b)
A_broken = np.array([[-400.6, 199.8],
                    [1198.8, -600.4]])
x_broken = Gauss2(A_broken, b)

In [146]:
x, x_broken

(array([-135.99601594, -272.01195219]), array([-203.996, -408.012]))

In [147]:
delta_A = linalg.norm(A_broken - A, ord=np.inf) / linalg.norm(A, ord=np.inf)
delta_A

0.003765227021041012

In [148]:
delta_x = linalg.norm(x_broken - x, ord=np.inf) / linalg.norm(x, ord=np.inf)
delta_x

0.4999782057854324