In [8]:
import numpy as np
import numpy.linalg as linalg

import warnings
warnings.filterwarnings('ignore')

In [9]:
def gauss2(A, b):
    a12_1 = A[0, 1] / A[0, 0]
    b1_1 = b[0] / A[0, 0]
    a22_1 = A[1, 1] - A[1, 0] * a12_1
    b2_1 = b[1] - A[1, 0] * b1_1
    b2_2 = b2_1 / a22_1
    x2 = b2_2
    x1 = b1_1 - a12_1 * x2
    return np.array([x1, x2])

In [38]:
def gaussWithMainElem(M):
    n, _ = M.shape
    bflags = [[False for _ in range(n + 1)] for _ in range(n)]
    for k in range(n):
        print(M)
        print('\n')
        main_elem_i = 0
        main_elem_j = 0
        for i in range(n):
            for j in range(n):
                if not bflags[i][j] and M[main_elem_i, main_elem_j] < abs(M[i, j]):
                    main_elem_i = i
                    main_elem_j = j
        m = []
        for i in range(n):
            m.append(M[i, main_elem_j] / M[main_elem_i, main_elem_j])
        for i in range(n):
            if i != main_elem_i:
                for j in range(n + 1):
                    if not bflags[i][j]:
                        M[i, j] -= M[main_elem_i, j] * m[i]
        for i in range(n):
            bflags[i][main_elem_j] = True
            bflags[main_elem_i][i] = True
        bflags[main_elem_i][n] = True
    print(M)
    print('\n')    
    super_threshold_indices = np.abs(M) < 10 ** -4
    M[super_threshold_indices] = 0
    
    print(M)
    print('\n')

    zero_count = [np.count_nonzero(M[i]) for i in range(n)]
    M = np.array([x for _, x in sorted(zip(zero_count, M), key=lambda pair: pair[0])])

    x = [None] * n
    for i in range(n):
        a = 0
        x_index = -1
        for j in range(n):
            if M[i, j] != 0:
                if x[j] is None:
                    x_index = j
                else:
                    a += x[j] * M[i, j]
        x[x_index] = (M[i, n] - a) / M[i, x_index]

    return x

## Задание А

$k = 6$

In [39]:
k = 6
M1 = np.array([
    [10 ** -5, 1, 2 + 0.1 * 6],
    [2, 0.5, 0.543]
])
M2 = np.array([
    [10 ** -5, 1 + 0.1 * k, 2],
    [2, 0.5, 8.765]
])

In [40]:
gauss2(M1[:, :2], M1[:, 2]).tolist()

[-0.37850094624445774, 2.600003785009463]

In [41]:
gaussWithMainElem(M1)

[[1.00e-05 1.00e+00 2.60e+00]
 [2.00e+00 5.00e-01 5.43e-01]]


[[0.         0.9999975  2.59999729]
 [2.         0.5        0.543     ]]


[[0.         0.9999975  2.59999729]
 [2.         0.5        0.543     ]]


[[0.         0.9999975  2.59999729]
 [2.         0.5        0.543     ]]




[-0.3785009462523657, 2.600003785009463]

In [42]:
gauss2(M2[:, :2], M2[:, 2]).tolist()

[4.0700063593976665, 1.2499745624602536]

In [43]:
gaussWithMainElem(M2)

[[1.000e-05 1.600e+00 2.000e+00]
 [2.000e+00 5.000e-01 8.765e+00]]


[[0.         1.5999975  1.99995617]
 [2.         0.5        8.765     ]]


[[0.         1.5999975  1.99995617]
 [2.         0.5        8.765     ]]


[[0.         1.5999975  1.99995617]
 [2.         0.5        8.765     ]]




[4.070006359384937, 1.2499745624602536]

## Задание Б

### 1)

$k = 6$

In [44]:
D = np.array([
    [3, 1, 2, 4],
    [-5, 2, 6, 7],
    [0, 3, 4, 1],
    [0, 0, -5, -6]
])
C = np.array([
    [-0.9, 0.7, 0.8, -0.5],
    [0.6, -0.5, 0.4, 0.3],
    [0, 0.3, 0.8, -0.9],
    [0, 0, 0.7, 0.6]
])
A = D + k * C
b = np.array([4, -13, 1, -5]).T

In [45]:
A

array([[-2.4,  5.2,  6.8,  1. ],
       [-1.4, -1. ,  8.4,  8.8],
       [ 0. ,  4.8,  8.8, -4.4],
       [ 0. ,  0. , -0.8, -2.4]])

In [46]:
gaussWithMainElem(np.column_stack([A, b]))

[[ -2.4   5.2   6.8   1.    4. ]
 [ -1.4  -1.    8.4   8.8 -13. ]
 [  0.    4.8   8.8  -4.4   1. ]
 [  0.    0.   -0.8  -2.4  -5. ]]


[[ -2.24090909   5.31363636   5.84545455   0.           5.47727273]
 [ -1.4         -1.           8.4          8.8        -13.        ]
 [ -0.7          4.3         13.           0.          -5.5       ]
 [ -0.38181818  -0.27272727   1.49090909   0.          -8.54545455]]


[[ -1.92615385   3.38013986   0.           0.           7.95034965]
 [ -1.4         -1.           8.4          8.8        -13.        ]
 [ -0.7          4.3         13.           0.          -5.5       ]
 [ -0.30153846  -0.76587413   0.           0.          -7.91468531]]


[[ -1.92615385   3.38013986   0.           0.           7.95034965]
 [ -1.4         -1.           8.4          8.8        -13.        ]
 [ -0.7          4.3         13.           0.          -5.5       ]
 [ -0.73796756   0.           0.           0.          -6.1132903 ]]


[[ -1.92615385   3.38013986   0.        

[8.283955324302504, 7.072642863550734, -2.316430429712031, 2.8554768099040113]

In [47]:
linalg.solve(A, b).tolist()

[8.283955324302502, 7.072642863550732, -2.3164304297120304, 2.8554768099040104]

### 2) е

In [48]:
M = np.array([  [0.82816 * 10 ** -4, -0.45368, 4.76448, 5.18823],
                [0.76816, -0.45368, 1.99448, 2.59372],
                [1.04816 * 10 ** -4, 1.14632, 1.44448, 3.11885]])
x = gaussWithMainElem(M)
x

[[ 8.28160e-05 -4.53680e-01  4.76448e+00  5.18823e+00]
 [ 7.68160e-01 -4.53680e-01  1.99448e+00  2.59372e+00]
 [ 1.04816e-04  1.14632e+00  1.44448e+00  3.11885e+00]]


[[ 8.28160000e-05 -4.53680000e-01  4.76448000e+00  5.18823000e+00]
 [ 7.68125332e-01 -2.63763013e-01  0.00000000e+00  4.21852142e-01]
 [ 7.97081067e-05  1.28386527e+00  0.00000000e+00  1.54589881e+00]]


[[ 8.28160000e-05 -4.53680000e-01  4.76448000e+00  5.18823000e+00]
 [ 7.68141708e-01  0.00000000e+00  0.00000000e+00  7.39448496e-01]
 [ 7.97081067e-05  1.28386527e+00  0.00000000e+00  1.54589881e+00]]


[[ 8.28160000e-05 -4.53680000e-01  4.76448000e+00  5.18823000e+00]
 [ 7.68141708e-01  0.00000000e+00  0.00000000e+00  7.39448496e-01]
 [ 7.97081067e-05  1.28386527e+00  0.00000000e+00  1.54589881e+00]]


[[ 0.         -0.45368     4.76448     5.18823   ]
 [ 0.76814171  0.          0.          0.7394485 ]
 [ 0.          1.28386527  0.          1.54589881]]




[0.9626459402598427, 1.2040973844744598, 1.2035951250479324]

In [49]:
linalg.solve(M[:, :3], M[:, 3]).tolist()

[0.9626459402598427, 1.2040973844744598, 1.2035951250479324]